-- 007_create_prospects.sql
CREATE TABLE IF NOT EXISTS prospects (
  id                CHAR(36) PRIMARY KEY,
  full_name         VARCHAR(200) NOT NULL,
  phone             VARCHAR(20) NOT NULL,
  email             VARCHAR(255),
  interested_service VARCHAR(255),
  service_id        CHAR(36),
  source            VARCHAR(50) DEFAULT 'whatsapp',
  status            ENUM('new','contacted','qualified','converted','lost') NOT NULL DEFAULT 'new',
  n8n_workflow_id   VARCHAR(100),
  n8n_execution_id  VARCHAR(100),
  conversation_log  JSON,
  raw_payload       JSON,
  assigned_to       CHAR(36),
  notes             TEXT,
  matched_user_id   CHAR(36),
  matched_at        TIMESTAMP NULL,
  first_contacted_at TIMESTAMP NULL,
  converted_at      TIMESTAMP NULL,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_prospects_phone (phone),
  INDEX idx_prospects_status (status),
  INDEX idx_prospects_n8n_execution (n8n_execution_id),
  INDEX idx_prospects_created (created_at),
  FOREIGN KEY (service_id) REFERENCES services(id),
  FOREIGN KEY (assigned_to) REFERENCES users(id),
  FOREIGN KEY (matched_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
